name: 'SSH Remote Commands'
description: 'Executing remote ssh commands'
author: 'ulturgashev'
inputs:
  host:
    description: 'ssh host'
  port:
    description: 'ssh port'
    default: 22
  passphrase:
    description: 'ssh key passphrase'
  username:
    description: 'ssh username'
  password:
    description: 'ssh password'
  key:
    description: 'content of ssh private key. ex raw content of ~/.ssh/id_rsa'
  key_path:
    description: 'path of ssh private key'
  script:
    description: 'execute commands'
  script_stop:
    description: 'stop script after first failure'
    default: false
  envs:
    description: 'pass environment variable to shell script'
  debug:
    description: 'enable debug mode'
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'terminal'
  color: 'gray-dark'
