name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag notifier:$(date +%s)
  
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Push to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ulturgashev/notifier/notifier
        tag_with_ref: true
        tags: latest

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      env:
        E_TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        E_CHAT_ID: ${{ secrets.CHAT_ID }}
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        port: ${{ secrets.DEPLOY_PORT }}
        envs: E_TELEGRAM_TOKEN,E_CHAT_ID
        script: |
          docker pull docker.pkg.github.com/ulturgashev/notifier/notifier:latest
          docker run --rm -d -p 8888:8080 --env TELEGRAM_TOKEN=$E_TELEGRAM_TOKEN --env CHAT_ID=$E_CHAT_ID docker.pkg.github.com/ulturgashev/notifier/notifier
